package views.frames;

import controllers.controller.ControlVista;
import java.awt.Color;
import java.util.List;
import dtos.JugadorDTO;

/**
 *
 * @author Knocmare
 */
public class FrmLobby extends javax.swing.JFrame {

    /**
     * Creates new form FrmLobby
     */
    public FrmLobby() {
        initComponents();
    }

    /**
     * Actualiza la vista del lobby con la lista de jugadores
     * @param jugadores Lista de jugadores en formato DTO
     */
    public void actualizarLobby(List<JugadorDTO> jugadores) {
        if (jugadores == null || jugadores.isEmpty()) {
            lblJugadorUno.setText("(Esperando)");
            pnlEstadoUno.setBackground(Color.RED);
            lblJugadorDos.setText("(Esperando)");
            pnlEstadoDos.setBackground(Color.RED);
            return;
        }

        if (jugadores.size() > 1) {
            // Jugador 1
            lblJugadorUno.setText(jugadores.get(0).getNombre());
            pnlEstadoUno.setBackground(Color.GREEN);
            // Jugador 2
            lblJugadorDos.setText(jugadores.get(1).getNombre());
            pnlEstadoDos.setBackground(Color.GREEN);
        } else {
            // Jugador 1
            lblJugadorUno.setText(jugadores.get(0).getNombre());
            pnlEstadoUno.setBackground(Color.GREEN);
            // Jugador 2
            lblJugadorDos.setText("(Buscando)");
            pnlEstadoDos.setBackground(Color.RED);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlJugadorUno = new javax.swing.JPanel();
        lblJugadorUno = new javax.swing.JLabel();
        pnlEstadoUno = new javax.swing.JPanel();
        pnlJugadorDos = new javax.swing.JPanel();
        lblJugadorDos = new javax.swing.JLabel();
        pnlEstadoDos = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnEmpezar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        pnlJugadorUno.setBackground(new java.awt.Color(255, 255, 255));
        pnlJugadorUno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblJugadorUno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJugadorUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadorUno.setText("JUGADOR 1");

        pnlEstadoUno.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlEstadoUnoLayout = new javax.swing.GroupLayout(pnlEstadoUno);
        pnlEstadoUno.setLayout(pnlEstadoUnoLayout);
        pnlEstadoUnoLayout.setHorizontalGroup(
            pnlEstadoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlEstadoUnoLayout.setVerticalGroup(
            pnlEstadoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlJugadorUnoLayout = new javax.swing.GroupLayout(pnlJugadorUno);
        pnlJugadorUno.setLayout(pnlJugadorUnoLayout);
        pnlJugadorUnoLayout.setHorizontalGroup(
            pnlJugadorUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblJugadorUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlJugadorUnoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(pnlEstadoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnlJugadorUnoLayout.setVerticalGroup(
            pnlJugadorUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadorUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJugadorUno)
                .addGap(48, 48, 48)
                .addComponent(pnlEstadoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pnlJugadorDos.setBackground(new java.awt.Color(255, 255, 255));
        pnlJugadorDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblJugadorDos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJugadorDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJugadorDos.setText("JUGADOR 2");

        pnlEstadoDos.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlEstadoDosLayout = new javax.swing.GroupLayout(pnlEstadoDos);
        pnlEstadoDos.setLayout(pnlEstadoDosLayout);
        pnlEstadoDosLayout.setHorizontalGroup(
            pnlEstadoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlEstadoDosLayout.setVerticalGroup(
            pnlEstadoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlJugadorDosLayout = new javax.swing.GroupLayout(pnlJugadorDos);
        pnlJugadorDos.setLayout(pnlJugadorDosLayout);
        pnlJugadorDosLayout.setHorizontalGroup(
            pnlJugadorDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblJugadorDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugadorDosLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(pnlEstadoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        pnlJugadorDosLayout.setVerticalGroup(
            pnlJugadorDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadorDosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJugadorDos)
                .addGap(48, 48, 48)
                .addComponent(pnlEstadoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnEmpezar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlJugadorUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpezar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlJugadorDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlJugadorUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlJugadorDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnEmpezar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblJugadorDos;
    private javax.swing.JLabel lblJugadorUno;
    private javax.swing.JPanel pnlEstadoDos;
    private javax.swing.JPanel pnlEstadoUno;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlJugadorDos;
    private javax.swing.JPanel pnlJugadorUno;
    // End of variables declaration//GEN-END:variables
}
