/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.frames;

import java.awt.FlowLayout;
import models.entidades.Coordenadas;

/**
 *
 * @author guzman
 */
public class FrmPartidaEnCursoMetodoBotones extends javax.swing.JFrame {

    private PnlTableroJugador panelJugador;
    private PnlTableroBot panelBot;
    private CasillaButton[][] casillasJugador;
    private CasillaButton[][] casillasBot;

    /**
     * Creates new form FrmPartidaEnCurso
     */
    public FrmPartidaEnCursoMetodoBotones() {
        initComponents();

        panelJugador = new PnlTableroJugador();
        panelBot = new PnlTableroBot();

        inicializarTableros();

        this.setLayout(new FlowLayout(FlowLayout.CENTER, 40, 20)); // 40px entre paneles, 20px arriba/abajo
        this.add(panelJugador);
        this.add(panelBot);

        this.pack(); // ajusta tamaño automático
    }

    private void inicializarTableros() {
        int filas = 10, columnas = 10;

        casillasJugador = new CasillaButton[filas][columnas];
        casillasBot = new CasillaButton[filas][columnas];

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                casillasJugador[i][j] = new CasillaButton(new Coordenadas(i, j));
                panelJugador.add(casillasJugador[i][j]);

                casillasBot[i][j] = new CasillaButton(new Coordenadas(i, j));
                panelBot.add(casillasBot[i][j]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPartidaEnCursoMetodoBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPartidaEnCursoMetodoBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPartidaEnCursoMetodoBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPartidaEnCursoMetodoBotones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPartidaEnCursoMetodoBotones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
