package views.frames;

import buseventos.Mensaje;
import clientesocket.ClienteSocket;
import config.ConfiguracionRed;
import controllers.controller.ControlVista;
import controllers.controller.Controlador;
import controllers.controller.IControlador;
import java.util.HashMap;
import java.util.function.Consumer;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import models.builder.IJugadorBuilder;
import models.builder.JugadorBuilder;
import models.entidades.Jugador;
import models.enums.ColorJugador;
import models.enums.EstadoJugador;

/**
 *
 * @author Gael
 */
public class FrmRegistrarJugador extends javax.swing.JFrame {

    private IControlador controlador;
    private ButtonGroup grupoColores;
    /**
     * Creates new form RegistrarJugador
     */
    public FrmRegistrarJugador() {
        this.controlador = controlador;
        initComponents();
        configurarComponentesAdicionales();
        
    }
    
    private void configurarComponentesAdicionales() {
        grupoColores = new ButtonGroup();
        grupoColores.add(cBoxRojo);
        grupoColores.add(cBoxAzul);

        this.setLocationRelativeTo(null);
    }
    
    private ColorJugador getColorSeleccionado() {
        if (cBoxRojo.isSelected()) {
            return ColorJugador.ROJO;
        }
        if (cBoxAzul.isSelected()) {
            return ColorJugador.AZUL;
        }
        
        return null;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBattleShip = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        cBoxRojo = new javax.swing.JCheckBox();
        cBoxAzul = new javax.swing.JCheckBox();
        nombreJugador = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBattleShip.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        labelBattleShip.setText("BattleShip");

        labelNombre.setText("Nombre:");

        labelColor.setText("Color:");

        cBoxRojo.setBackground(new java.awt.Color(255, 0, 51));
        cBoxRojo.setText("Rojo");

        cBoxAzul.setBackground(new java.awt.Color(0, 0, 255));
        cBoxAzul.setText("Azul");
        cBoxAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAzulActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(0, 153, 0));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(labelBattleShip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelColor)
                                .addGap(18, 18, 18)
                                .addComponent(cBoxRojo)
                                .addGap(18, 18, 18)
                                .addComponent(cBoxAzul)))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelBattleShip, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cBoxRojo)
                        .addComponent(cBoxAzul)))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnRegresar))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxAzulActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        String nombre = nombreJugador.getText().trim();
        if (nombre.isEmpty() || nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre.");
            return;
        }
        ColorJugador colorSeleccionado = getColorSeleccionado();
        if (colorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Color no válido. Por favor selecciona ROJO o AZUL.");
            return;
        }
        
        IJugadorBuilder builder = new JugadorBuilder();
        builder.setNombre(nombre);
        builder.setColor(colorSeleccionado);
        builder.setEstado(EstadoJugador.JUGANDO);
        Jugador nuevoJugador = builder.getResult();

        // Intentar conectar al servidor
        try {
            // Crear modelo
            models.control.ControlModelo modelo = new models.control.ControlModelo(new java.util.ArrayList<>());
            HashMap<String, Consumer<Mensaje>> manejadores = new HashMap<>();

            // Crear cliente con controlador temporal (null)
            ClienteSocket cliente = new ClienteSocket(
                    ConfiguracionRed.SERVIDOR_HOST,
                    ConfiguracionRed.SERVIDOR_PUERTO,
                    null
            );

            // Conectar al servidor
            cliente.execute();

            // Crear controlador con modelo y cliente ya conectado
            Controlador controladorImpl = new Controlador(modelo, cliente, manejadores);

            // Actualizar el cliente con el controlador correcto
            cliente.setControl(controladorImpl);

            // Configurar ControlVista
            ControlVista.getInstancia().setControl(controladorImpl);

            // Crear lobby y suscribirlo al modelo
            FrmLobbyMejorado lobby = new FrmLobbyMejorado(nuevoJugador);
            modelo.suscribirAPartida(lobby);

            // Unirse a la partida
            ControlVista.getInstancia().unirsePartida(nuevoJugador);

            lobby.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo conectar al servidor en " +
                            ConfiguracionRed.SERVIDOR_HOST + ":" +
                            ConfiguracionRed.SERVIDOR_PUERTO +
                            "\n\nAsegurate de que el servidor este corriendo.",
                    "Error de conexion",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmMenuPrincipal m = new FrmMenuPrincipal();
        m.setVisible(true);
        m.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarJugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox cBoxAzul;
    private javax.swing.JCheckBox cBoxRojo;
    private javax.swing.JLabel labelBattleShip;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreJugador;
    // End of variables declaration//GEN-END:variables
}
