package cliente.presentacion.componentes;

import java.awt.Dimension;

/**
 * Panel contenedor para el tablero del jugador.
 * Es un grid de 10x10 donde van las casillas. Netbeans lo genera automatico.
 *
 * @author Freddy Ali Castro Roman - 252191
 * @author Christopher Alvarez Centeno - 251954
 * @author Ethan Gael Valdez Romero - 253298
 * @author Daniel Buelna Andujo - 260378
 * @author Angel Ruiz Garcia - 248171
 */
public class PnlTableroJugador extends javax.swing.JPanel {

    /**
     * Creates new form PnlTableroJugador
     */
    public PnlTableroJugador() {
        initComponents();
        setPreferredSize(new Dimension(300, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(10, 10));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
