package dtos.enums;

public enum ResultadoAddNaveDTO {
    JUGADOR_NULL,
    NAVE_NULL,
    COORDENADAS_NULL,
    JUGADOR_NO_ENCONTRADO,
    COORDENADAS_EXTRA,
    COORDENADAS_FUERA_LIMITE,
    NO_ORDENADA_VERTICALMENTE,
    NO_ORDENADA_HORIZONTALMENTE,
    NO_CONSECUTIVO_X,
    NO_CONSECUTIVO_Y,
    ESPACIO_YA_OCUPADO,
    NAVE_AÑADIDA;
}
