package cliente.presentacion.frames;

import cliente.controlador.ControlVista;
import compartido.comunicacion.dto.RespuestaUnirseDTO;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import cliente.negocio.builder.IJugadorBuilder;
import cliente.negocio.builder.JugadorBuilder;
import compartido.enums.ColorJugador;
import compartido.enums.EstadoJugador;
import compartido.observador.ISuscriptor;
import compartido.comunicacion.dto.JugadorDTO;
import compartido.entidades.Jugador;

/**
 * Pantalla donde pones tu nombre y escoges de que color quieres tus naves.
 * Es como el "registro" antes de entrar a una partida.
 *
 * @author Freddy Ali Castro Roman - 252191
 * @author Christopher Alvarez Centeno - 251954
 * @author Ethan Gael Valdez Romero - 253298
 * @author Daniel Buelna Andujo - 260378
 * @author Angel Ruiz Garcia - 248171
 */
public class FrmRegistrarJugador extends javax.swing.JFrame implements ISuscriptor {

    private ButtonGroup grupoColores;
    private ControlVista cv;
    private Map<String, Consumer<Object>> manejadoresNoti;
    private boolean esperandoRespuesta;

    /**
     * Creates new form RegistrarJugador
     */
    public FrmRegistrarJugador() {
        initComponents();
        configurarComponentesAdicionales();
        this.cv = ControlVista.getInstancia();
        this.esperandoRespuesta = false;
        initManejadores();
        cv.suscribirLobby(this);
    }

    private void initManejadores() {
        manejadoresNoti = new HashMap<>();
        manejadoresNoti.put("ERROR_UNIRSE", this::manejarErrorUnirse);
    }

    @Override
    public void notificar(String contexto, Object datos) {
        Consumer<Object> manejador = manejadoresNoti.get(contexto);
        if (manejador != null) {
            SwingUtilities.invokeLater(() -> manejador.accept(datos));
        }
    }

    private void manejarErrorUnirse(Object datos) {
        if (datos instanceof RespuestaUnirseDTO respuesta) {
            esperandoRespuesta = false;
            btnContinuar.setEnabled(true);
            nombreJugador.setEnabled(true);

            JOptionPane.showMessageDialog(this,
                    respuesta.getMensaje(),
                    "Error al unirse",
                    JOptionPane.ERROR_MESSAGE);

            // Limpiar el campo de nombre para que ingrese otro
            nombreJugador.setText("");
            nombreJugador.requestFocus();
        }
    }

    private void configurarComponentesAdicionales() {
        grupoColores = new ButtonGroup();
        grupoColores.add(cBoxRojo);
        grupoColores.add(cBoxAzul);

        this.setLocationRelativeTo(null);
    }

    private ColorJugador getColorSeleccionado() {
        if (cBoxRojo.isSelected()) {
            return ColorJugador.ROJO;
        }
        if (cBoxAzul.isSelected()) {
            return ColorJugador.AZUL;
        }

        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBattleShip = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        cBoxRojo = new javax.swing.JCheckBox();
        cBoxAzul = new javax.swing.JCheckBox();
        nombreJugador = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelBattleShip.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        labelBattleShip.setText("BattleShip");

        labelNombre.setText("Nombre:");

        labelColor.setText("Color:");

        cBoxRojo.setBackground(new java.awt.Color(255, 0, 51));
        cBoxRojo.setText("Rojo");

        cBoxAzul.setBackground(new java.awt.Color(0, 0, 255));
        cBoxAzul.setText("Azul");
        cBoxAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAzulActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(0, 153, 0));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(labelBattleShip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelColor)
                                .addGap(18, 18, 18)
                                .addComponent(cBoxRojo)
                                .addGap(18, 18, 18)
                                .addComponent(cBoxAzul)))))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelBattleShip, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cBoxRojo)
                        .addComponent(cBoxAzul)))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnRegresar))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBoxAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxAzulActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        String nombre = nombreJugador.getText().trim();
        if (nombre.isEmpty() || nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre.");
            return;
        }
        ColorJugador colorSeleccionado = getColorSeleccionado();
        if (colorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Color no válido. Por favor selecciona ROJO o AZUL.");
            return;
        }

        IJugadorBuilder builder = new JugadorBuilder();
        builder.setNombre(nombre);
        builder.setColor(colorSeleccionado);
        builder.setEstado(EstadoJugador.JUGANDO);
        Jugador jugador = builder.getResult();
        JugadorDTO nuevoJugador = new JugadorDTO(jugador.getNombre(), jugador.getColor(), jugador.getEstado());
        this.cv.unirsePartida(nuevoJugador);

        FrmLobby lobby = new FrmLobby();
        lobby.setLocationRelativeTo(this);
        lobby.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmMenuPrincipal m = new FrmMenuPrincipal();
        m.setVisible(true);
        m.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox cBoxAzul;
    private javax.swing.JCheckBox cBoxRojo;
    private javax.swing.JLabel labelBattleShip;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreJugador;
    // End of variables declaration//GEN-END:variables
}
