package models.enums;

/**
 *
 * @author daniel
 */
public enum ResultadoAddNave {
    JUGADOR_NULL,
    NAVE_NULL,
    COORDENADAS_NULL,
    JUGADOR_NO_ENCONTRADO,
    COORDENADAS_EXTRA,
    COORDENADAS_FUERA_LIMITE,
    NO_ORDENADA_VERTICLMENTE,
    NO_ORDENADA_HORIZONTALMENTE,
    NO_CONSECUTIVO_X,
    NO_CONSECUTIVO_Y,
    ESPACIO_YA_OCUPADO,
    NAVE_AÑADIDA,
    CANTIDAD_NAVES_EXCEDIDA;
}
